### ISSUE TITLE
Cannot run grpc tests with relative importPath in client.load

### ISSUE THREAD

**Issue by SuveenVundavalli** [mbolotov/k6-intellij-plugin#11]
With the following file structure:
```
❯ tree .
.
├── K6
│     ├── SmokeTestFramework
│     │     └── CoffeeReadyEmptyNameSmokeTest.js
└── proto
    └── theBusyBean
        └── CoffeeMaker.proto
```

and the following code in `CoffeeReadyEmptyNameSmokeTest.js`

```{.javascript .numberLines .lineAnchors}
import grpc from 'k6/net/grpc';
import {check} from "k6";

const client = new grpc.Client();

client.load(['../../proto/theBusyBean'], 'CoffeeMaker.proto');

export default () => {
    client.connect('localhost:50051', {
        plaintext: true,
    });

    const order = "White Coffee";

    const params = {ClientName: "", Order: order};

    const response = client.invoke('test.logic.CoffeeMaker.CoffeeShopService/CoffeeReady', params);

    check(response, {
        'need clientname': (r) => r.status === grpc.StatusInvalidArgument,
    });


    client.close()

}
```

I see run button to the left of `export default () => {`.

But it returns in the following error:

```
k6 run /var/folders/pm/v0wmsjz114q453d5qx21svrc0000gp/T/CoffeeReadyEmptyNameSmokeTest.js
Testing started at 10:40 am ...

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

ERRO[0000] GoError: ../proto/theBusyBean/CoffeeMaker.proto: stat /var/folders/pm/v0wmsjz114q453d5qx21svrc0000gp/proto/theBusyBean/CoffeeMaker.proto: no such file or directory
	at reflect.methodValueCall (native)
	at file:///Users/somename/Documents/Repos/testing-repos/UdemyGRPCService-main/UdemyGRPCK6Incomplete/com.github.grpc/src/main/K6/SmokeTestFramework/CoffeeReadyEmptyNameSmokeTest.js:6:12(36)
	at go.k6.io/k6/js.(*requireImpl).require-fm (native)
	at file:///var/folders/pm/v0wmsjz114q453d5qx21svrc0000gp/T/CoffeeReadyEmptyNameSmokeTest.js:4:21(30)  hint="script exception"
```

The same works fine if I change path to absolute path or if I run in terminal using `k6 run CoffeeReadyEmptyNameSmokeTest.js`

I use `IntelliJ IDEA 2023.2.4 (Ultimate Edition)` with k6 plugin version`0.3.0` on `Apple M2 Macbook Pro`

**Comment by mbolotov** [comment]
Hey @SuveenVundavalli, 
could you try the `1.0.1` version?
it has fixed the working directory detection which could be the root cause of your problem.

**Comment by mbolotov** [comment]
closing as no response received in 2 months,
please create a new one if the problem persists
